[package]
name = "nauty-colourings"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
hashbrown = "0.14"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[build-dependencies]
cc = "1.0"
